#cloud-config

write_files:
  %{~ for f in files ~}
  - path: /run/app/${f.filename}
    permissions: 0644
    content: ${f.content}
    encoding: b64
  %{~ endfor ~}
  %{~ for c in docker_compose_files ~}
  - path: /etc/systemd/system/${coalesce(c.name, "app")}.service
    permissions: 0644
    content: |
      [Unit]
      Description=Docker Compose Service (${coalesce(c.name, "app")})
      Requires=docker.service
      After=docker.service

      [Service]
      Type=simple
      WorkingDirectory=/run/app
      Environment=HOME=/run/app TMP=/run/app/.tmp
      PassEnvironment=HOME TMP
      ExecStartPre=-/run/app/.bin/docker-compose -f ${c.filename} rm -f
      ExecStart=/run/app/.bin/docker-compose -f ${c.filename} up
      ExecStop=/run/app/.bin/docker-compose -f ${c.filename} stop -t 15
      ExecStopPost=-/run/app/.bin/docker-compose -f ${c.filename} rm -f

      [Install]
      WantedBy=multi-user.target

  %{~ endfor ~}

runcmd:
  - set -x
  - mkdir -p /run/app/.bin
  - mkdir -p /run/app/.tmp
  - "[ $(docker network list -q --filter=name=web) ] || docker network create web"
  - |
    if [ ! -f /run/app/.bin/docker-compose ]; then
      curl --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 90 \
        -LJ "https://github.com/docker/compose/releases/download/1.26.1/docker-compose-$(uname -s)-$(uname -m)" \
        -o /run/app/.bin/docker-compose
      chmod +x /run/app/.bin/docker-compose
    fi
  - systemctl daemon-reload
  - systemctl enable --now traefik app
