version: "3"
services:
  traefik:
    container_name: traefik
    image: traefik:${TRAEFIK_VERSION:-latest}
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - '--providers.docker.defaultrule=Host(`{{ index .Labels "com.docker.compose.service"}}.${DOMAIN}`)'
      - "--providers.docker.network=${DOCKER_NETWORK:-web}"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--entrypoints.admin.address=:${TRAEFIK_ADMIN_PORT:-9000}"
      - "--entrypoints.admin.http.tls=letsencrypt"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=letsencrypt"
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.caserver=${LETSENCRYPT_SERVER:-https://acme-v02.api.letsencrypt.org/directory}"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    env_file:
      - ".env"
    ports:
      - "80:80"
      - "443:443"
      - "${TRAEFIK_ADMIN_PORT:-9000}:${TRAEFIK_ADMIN_PORT:-9000}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ./traefik/:/etc/traefik/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=admin"
      - "traefik.http.routers.traefik.rule=Host(`${DOMAIN}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
      - "traefik.http.routers.traefik.middlewares=admin"
      - "traefik.http.middlewares.admin.basicauth.users=admin:${TRAEFIK_ADMIN_PASSWORD}"

networks:
  default:
    external:
      name: ${DOCKER_NETWORK:-web}
