version: "3"
services:
  traefik:
    container_name: traefik
    image: traefik:2.4
    restart: always
    env_file:
      - ".env"
      - ".env.traefik"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ${APPDIR:-/var/app}/traefik:/etc/traefik
      - ${APPDIR:-/var/app}/acme:/acme
    labels: ["traefik.enable=false"]
networks:
  default:
    external:
      name: ${DOCKER_NETWORK:-traefik}
