version: 3
services:
  webhook:
    restart: unless-stopped
    image: almir/webhook
    container_name: webhook
    command:
      - -verbose
      - -port=${TRAEFIK_OPS_PORT-9000}
      - -hooks=/app/.webhook/hooks.json
      - -urlprefix=webook
      - -http-methods=PATCH
      - -hotreload
    volumes:
      - ./:/app
    ports:
      - ${TRAEFIK_OPS_PORT-9000}
    labels:
      - traefik.enable=${WEBHOOK_ENABLED-false}
      - traefik.http.routers.webhook.rule=Host(`${DOMAIN}`) && PathPrefix(`/webook`)
      - traefik.http.routers.webhook.entrypoints=admin
networks:
  default:
    external:
      name: ${DOCKER_NETWORK}
