version: 3.3
services:
  traefik:
    restart: unless-stopped
    image: traefik:${TRAEFIK_IMAGE_TAG:-latest}
    container_name: traefik
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=true
      - --providers.docker.network=${DOCKER_NETWORK}
      - --providers.docker.defaultRule=Host(`{{ index .Labels "com.docker.compose.service"}}.${DOMAIN}`)
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entryPoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=letsencrypt
      - --entrypoints.admin.address=:${TRAEFIK_OPS_PORT:-9000}
      - --entrypoints.admin.http.tls=letsencrypt
      - --certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json
      - --certificatesresolvers.letsencrypt.acme.caserver=${LETSENCRYPT_SERVER:-https://acme-staging-v02.api.letsencrypt.org/directory}
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --log.level=info
    ports:
      - 80:80
      - 443:443
      - ${TRAEFIK_OPS_PORT-9000}:${TRAEFIK_OPS_PORT-9000}
    volumes:
      - ./.traefik:/traefik
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.rule=Host(`${DOMAIN}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      - traefik.http.routers.traefik.entrypoints=admin
networks:
  default:
    external:
      name: ${DOCKER_NETWORK}
